merge process updates

diff --git a/.docker/docker-entrypoint b/.docker/docker-entrypoint
--- a/.docker/docker-entrypoint
+++ b/.docker/docker-entrypoint
@@ -1,4 +1,5 @@
-<?php
+#!/usr/bin/env bash
+
 # Mattermost User Merge Tool
 
 # Copyright (c) 2023 Maxwell Power
@@ -13,21 +14,49 @@
 # AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
-?>
+if [ "$1" = 'start' ]; then
 
-<!DOCTYPE html>
-<html lang="en">
-<head>
-    <meta charset="utf-8">
-    <meta name="handheldfriendly" content="true">
-    <meta name="viewport" content="width=device-width, initial-scale=1">
-    <title>Mattermost User Account Merge Tool</title>
-    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
-          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
-          crossorigin="anonymous">
-    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
-    <link rel="stylesheet" href="css/main.css">
-</head>
+  function _redirect_io() {
+    ln -sf /proc/1/fd/0 /dev/stdin
+    ln -sf /proc/1/fd/1 /dev/stdout
+    ln -sf /proc/1/fd/2 /dev/stderr
+  }
 
-<body>
-<div class="container">
+  function _start_system_services() {
+    echo "Starting syslog ..."
+    systemctl start rsyslog
+
+    echo "Starting apache2 ..."
+    systemctl start apache2
+
+    echo "Checking Services after startup ..."
+
+    echo "Checking syslog ..."
+    systemctl status rsyslog || exit 1
+
+    echo "Checking Apache2 ..."
+    systemctl status apache2 || exit 1
+  }
+
+  echo "Starting Container"
+
+  echo "Check Environment Variables ..."
+  if [ -n "${DB_HOST}" ] && [ -n "${DB_USER}" ] && [ -n "${DB_PASSWORD}" ] && [ -n "${DB_NAME}" ]; then
+    echo "Found Database Credentials"
+  else
+    echo "ERROR: Missing SQL Environment Variables"
+    exit 1
+  fi
+
+  echo "Redirecting I/O ..."
+  _redirect_io
+
+  echo "Starting System SERVICES ..."
+  _start_system_services
+  echo "DONE: Starting SERVICES"
+
+  echo "Passing container process control to HEALTHCHECK ..."
+  exec docker-healthcheck
+else
+  exec "$@"
+fi
